name: farm-app
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
    networks:
      - farm-app-network
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db 
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - farm-app-network
  frontend:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend/:/home/node/app
    expose:
      - "5173"
    ports:
      - "5173:5173"
    command: ["/bin/sh", "-c", "npm install && npm run dev -- --host"]

    networks:
      - farm-app-network

  backend:
    image: farm-app/backend
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app
    expose:
      - "3001"
    ports:
      - "3001:3001"
    environment:
      - DEBUG=true
    env_file:
      - path: ./.env
        required: true
    networks:
      - farm-app-network

networks:
  farm-app-network:
    driver: bridge

volumes:
  mongo_data: